name: Android Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: 'true'

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '17'

      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Install Appium
        run: sudo npm install -g appium --unsafe-perm=true --allow-root

      - name: Install uiautomator2
        run: appium driver install uiautomator2

      - name: Run Appium as daemon
        run: |
          nohup appium --allow-insecure=get_server_logs > appium.log 2>&1 &

      - name: Unzip APK
        run: |
          pwd
          ls -la
          tar -xf src/test/resources/android.tar.xz -C src/test/resources/

      - name: Start emulator and run tests
        uses: ReactiveCircus/android-emulator-runner@v2
        with:
          api-level: 28
          target: google_apis
          arch: x86_64
          profile: pixel
          emulator-options: -no-window -gpu swiftshader_indirect
          script: ./gradlew build

      - name: Upload JUnit test report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: junit-test-report
          path: build/reports/tests/test/

      - name: Upload appium artifacts
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: appium-log
          path: appium.log
