name: Android Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  ANDROID_SDK_PACKAGES: system-images;android-27;google_apis;arm64-v8a
  EMULATOR_TIMEOUT: 350
  EMULATOR_NAME: test_avd
  DEVICE_NAME: pixel
  ANDROID_AVD_HOME: /home/runner/.config/.android/avd

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    services:
      appium:
        image: appium/appium
        ports:
          - 4723:4723

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '17'

      - name: Download and setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Update SDK tools
        run: sdkmanager --update

      - name: Install system image
        run: sdkmanager "${{ env.ANDROID_SDK_PACKAGES }}"

      - name: Install platform tools
        run: sdkmanager "platform-tools"

      - name: Install emulator
        run: sdkmanager "emulator"

      - name: Start ADB server
        run: adb start-server

      - name: List available devices
        run: avdmanager list device

      - name: Create AVD
        run: echo "no" | avdmanager create avd -n ${{ env.EMULATOR_NAME }} -k "${{ env.ANDROID_SDK_PACKAGES }}" --device "${{ env.DEVICE_NAME }}"

      - name: List created AVDs
        run: avdmanager list avd

      - name: Check AVD files
        run: ls -al ~/.config/.android/avd/

      - name: Launch emulator
        run: |
          chmod +x ./start_emu_headless.sh
          source $GITHUB_ENV
          ./start_emu_headless.sh

      - name: Unzip APK
        run: |
          cd src/test/resources/
          tar -xf android.tar.xz

      - name: Run tests
        run: ./gradlew build
