name: Android Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  ANDROID_SDK_PACKAGES: system-images;android-28;google_apis;x86_64
  EMULATOR_TIMEOUT: 350
  EMULATOR_NAME: test_avd
  DEVICE_NAME: pixel
  ANDROID_AVD_HOME: /home/runner/.config/.android/avd

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: 'true'

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '17'

      - name: Download and setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Update SDK tools
        run: yes | sdkmanager --update

      - name: List available system images
        run: sdkmanager --list | grep "system-images"

      - name: Install system image
        run: sdkmanager "${{ env.ANDROID_SDK_PACKAGES }}"

      - name: Install platform tools
        run: sdkmanager "platform-tools"

      - name: Install emulator
        run: sdkmanager "emulator"

      - name: Start ADB server
        run: adb start-server

      - name: List available devices
        run: avdmanager list device

      - name: Create AVD
        run: echo "no" | avdmanager create avd -n ${{ env.EMULATOR_NAME }} -k "${{ env.ANDROID_SDK_PACKAGES }}" --device "${{ env.DEVICE_NAME }}"

      - name: List created AVDs
        run: avdmanager list avd

      - name: Check AVD files
        run: ls -al ~/.config/.android/avd/

      - name: Launch emulator
        run: |
          nohup $ANDROID_HOME/emulator/emulator @${{ env.EMULATOR_NAME }} -no-accel -no-window -no-snapshot -screen no-touch -noaudio -memory 2048 -no-boot-anim -gpu swiftshader_indirect &
          sleep 60
          adb wait-for-device
          adb shell settings put global window_animation_scale 0
          adb shell settings put global transition_animation_scale 0
          adb shell settings put global animator_duration_scale 0
          adb shell settings put global hidden_api_policy_pre_p_apps 1
          adb shell settings put global hidden_api_policy_p_apps 1
          adb shell settings put global hidden_api_policy 1

      - name: Unzip APK
        run: |
          pwd
          ls -la
          tar -xf src/test/resources/android.tar.xz -C src/test/resources/

      - name: Start Appium server with relaxed security
        run: |
          docker run -d --name appium -p 4723:4723 appium/appium --relaxed-security
          sleep 10

      - name: Run tests
        run: ./gradlew build

      - name: Upload JUnit test report
        uses: actions/upload-artifact@v3
        with:
          name: junit-test-report
          path: build/reports/tests/test/