name: Android Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      appium:
        image: appium/appium
        ports:
          - 4723:4723

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Download and setup Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 27
          target: google_apis
          arch: x86

      - name: Update SDK tools
        run: sdkmanager --update

      - name: Install system image
        run: sdkmanager "system-images;android-27;google_apis;x86"

      - name: Install platform tools
        run: sdkmanager "platform-tools"

      - name: Install emulator
        run: sdkmanager "emulator"

      - name: Set up environment variables
        run: echo "export ANDROID_SDK_ROOT=$ANDROID_HOME" >> $GITHUB_ENV
        shell: bash

      - name: Start ADB server
        run: adb start-server

      - name: Create AVD
        run: echo "no" | avdmanager create avd -n test -k "system-images;android-27;google_apis;x86" --device "pixel"

      - name: Start emulator
        run: |
          nohup $ANDROID_HOME/emulator/emulator -avd test -no-audio -no-window -gpu off -camera-back none -camera-front none &
          adb wait-for-device
          adb shell settings put global window_animation_scale 0 &
          adb shell settings put global transition_animation_scale 0 &
          adb shell settings put global animator_duration_scale 0 &
          sleep 60

      - name: Install dependencies
        run: ./gradlew assembleDebug assembleAndroidTest

      - name: Run tests
        run: ./gradlew connectedAndroidTest
